repository = grauwoelfchen/rust-vet-tools

build\:stable:
	@docker image build -t $(repository):stable stable
.PHONY: build\:stable

build\:nightly:
	@docker image build -t $(repository):nightly nightly
.PHONY: build\:nightly
