build\:amd64:
	@docker image build -t grauwoelfchen/gentoo:amd64 amd64
.PHONY: build\:amd64

build\:amd64-nomultilib
	@docker image build -t grauwoelfchen/gentoo:amd64-nomultilib amd64-nomultilib
.PHONY: build\:amd64-nomultilib
