build\:stable:
	@docker image build -t grauwoelfchen/rust:stable stable
.PHONY: build\:stable

build\:stable-fearless:
	@docker image build -t grauwoelfchen/rust:stable-fearless stable-fearless
.PHONY: build\:stable-fearless

build\:nightly:
	@docker image build -t grauwoelfchen/rust:nightly nightly
.PHONY: build\:nightly

build\:nightly-fearless:
	@docker image build -t grauwoelfchen/rust:nightly-fearless nightly-fearless
.PHONY: build\:nightly-fearless
